#!/bin/bash

if [ ! -z "$MYSQL_DATABASE" ]; then
echo "CREATE USER '$MYSQL_USER' IDENTIFIED BY '$MYSQL_PASSWORD'" | mysql -h $MYSQL_PORT_3306_TCP_ADDR -u $MYSQL_ENV_user --password=$MYSQL_ENV_password
echo "CREATE DATABASE $MYSQL_DATABASE" | mysql -h $MYSQL_PORT_3306_TCP_ADDR -u $MYSQL_ENV_user --password=$MYSQL_ENV_password
echo "GRANT ALL PRIVILEGES ON $MYSQL_DATABASE.* TO '$MYSQL_USER'@'%' WITH GRANT OPTION; FLUSH PRIVILEGES" | mysql -h $MYSQL_PORT_3306_TCP_ADDR -u $MYSQL_ENV_user --password=$MYSQL_ENV_password
fi